"""rework ondelete and nullable

Revision ID: 2d58e1b571b6
Revises: 5a529c897fdb
Create Date: 2024-05-21 11:35:28.083535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d58e1b571b6'
down_revision: Union[str, None] = '5a529c897fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tournament_flight_association_tournament_id_fkey', 'tournament_flight_association', type_='foreignkey')
    op.drop_constraint('tournament_flight_association_flight_id_fkey', 'tournament_flight_association', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_flight_association', 'flights', ['flight_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tournament_flight_association', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tournament_hole_association_table_hole_id_fkey', 'tournament_hole_association_table', type_='foreignkey')
    op.drop_constraint('tournament_hole_association_table_tournament_id_fkey', 'tournament_hole_association_table', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_hole_association_table', 'holes', ['hole_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tournament_hole_association_table', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_flight_association_flight_id_fkey', 'user_flight_association', type_='foreignkey')
    op.drop_constraint('user_flight_association_user_id_fkey', 'user_flight_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_flight_association', 'flights', ['flight_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_flight_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_tournament_association_tournament_id_fkey', 'user_tournament_association', type_='foreignkey')
    op.drop_constraint('user_tournament_association_user_id_fkey', 'user_tournament_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_tournament_association', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tournament_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tournament_association', type_='foreignkey')
    op.drop_constraint(None, 'user_tournament_association', type_='foreignkey')
    op.create_foreign_key('user_tournament_association_user_id_fkey', 'user_tournament_association', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_tournament_association_tournament_id_fkey', 'user_tournament_association', 'tournaments', ['tournament_id'], ['id'])
    op.drop_constraint(None, 'user_flight_association', type_='foreignkey')
    op.drop_constraint(None, 'user_flight_association', type_='foreignkey')
    op.create_foreign_key('user_flight_association_user_id_fkey', 'user_flight_association', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_flight_association_flight_id_fkey', 'user_flight_association', 'flights', ['flight_id'], ['id'])
    op.drop_constraint(None, 'tournament_hole_association_table', type_='foreignkey')
    op.drop_constraint(None, 'tournament_hole_association_table', type_='foreignkey')
    op.create_foreign_key('tournament_hole_association_table_tournament_id_fkey', 'tournament_hole_association_table', 'tournaments', ['tournament_id'], ['id'])
    op.create_foreign_key('tournament_hole_association_table_hole_id_fkey', 'tournament_hole_association_table', 'holes', ['hole_id'], ['id'])
    op.drop_constraint(None, 'tournament_flight_association', type_='foreignkey')
    op.drop_constraint(None, 'tournament_flight_association', type_='foreignkey')
    op.create_foreign_key('tournament_flight_association_flight_id_fkey', 'tournament_flight_association', 'flights', ['flight_id'], ['id'])
    op.create_foreign_key('tournament_flight_association_tournament_id_fkey', 'tournament_flight_association', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###
