"""add name in flight model

Revision ID: 54ab240491bf
Revises: 3670cc1e4ef2
Create Date: 2024-05-24 12:36:32.373346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ab240491bf'
down_revision: Union[str, None] = '3670cc1e4ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('name', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'flights', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flights', type_='unique')
    op.drop_column('flights', 'name')
    # ### end Alembic commands ###
