"""delete tournament hole association

Revision ID: d654637e734f
Revises: 0e1a3e61dcf9
Create Date: 2024-05-25 03:16:54.008406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd654637e734f'
down_revision: Union[str, None] = '0e1a3e61dcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_hole_association_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_hole_association_table',
    sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hole_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hole_id'], ['holes.id'], name='tournament_hole_association_table_hole_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name='tournament_hole_association_table_tournament_id_fkey', ondelete='CASCADE'),
    sa.UniqueConstraint('tournament_id', 'hole_id', name='idx_unique_tournament_hole')
    )
    # ### end Alembic commands ###
