"""create table Flights

Revision ID: 687da7e35f04
Revises: d91550c3116f
Create Date: 2024-05-21 01:09:28.866724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '687da7e35f04'
down_revision: Union[str, None] = 'd91550c3116f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('date_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_flight_association',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('flight_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.UniqueConstraint('user_id', 'flight_id', name='idx_unique_user_flight')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_flight_association')
    op.drop_table('flights')
    # ### end Alembic commands ###
