"""roolback

Revision ID: 337193f1b8eb
Revises: 5e0fa3c68448
Create Date: 2024-05-31 22:46:07.117340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337193f1b8eb'
down_revision: Union[str, None] = '5e0fa3c68448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('holes_id_course_fkey', 'holes', type_='foreignkey')
    op.create_foreign_key(None, 'holes', 'courses', ['id_course'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'holes', type_='foreignkey')
    op.create_foreign_key('holes_id_course_fkey', 'holes', 'courses', ['id_course'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
