"""create table tournaments and tournament_flight_association

Revision ID: 2af2a52c6ec9
Revises: 687da7e35f04
Create Date: 2024-05-21 01:17:17.521972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2af2a52c6ec9'
down_revision: Union[str, None] = '687da7e35f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
                    sa.Column('name', sa.String(length=300), nullable=False),
                    sa.Column('max_flights', sa.Integer(), nullable=False),
                    sa.Column('start', sa.DateTime(), nullable=False),
                    sa.Column('end', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('date_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tournament_flight_association',
                    sa.Column('tournament_id', sa.Integer(), nullable=False),
                    sa.Column('flight_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
                    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
                    sa.UniqueConstraint('tournament_id', 'flight_id', name='idx_unique_tournament_flight')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_flight_association')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
