"""create table user_tournament_association

Revision ID: 9b3273dc7c01
Revises: d21fd79accff
Create Date: 2024-05-21 09:46:04.990976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9b3273dc7c01'
down_revision: Union[str, None] = 'd21fd79accff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tournament_association',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('tournament_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.UniqueConstraint('user_id', 'tournament_id', name='idx_unique_user_tournament')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tournament_association')
    # ### end Alembic commands ###
