"""create table tournament_hole_association

Revision ID: ef97716c7956
Revises: cfcc23aec6eb
Create Date: 2024-05-21 01:33:40.038648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ef97716c7956'
down_revision: Union[str, None] = 'cfcc23aec6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_hole_association_table',
                    sa.Column('tournament_id', sa.Integer(), nullable=False),
                    sa.Column('hole_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['hole_id'], ['holes.id'], ),
                    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
                    sa.UniqueConstraint('tournament_id', 'hole_id', name='idx_unique_tournament_hole')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_hole_association_table')
    # ### end Alembic commands ###
