"""add status in tournament model

Revision ID: 0e1a3e61dcf9
Revises: 54ab240491bf
Create Date: 2024-05-24 16:47:52.756407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1a3e61dcf9'
down_revision: Union[str, None] = '54ab240491bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'status')
    # ### end Alembic commands ###
