"""create table Scores and TotalScores

Revision ID: 85707ff9c0b6
Revises: e77760fd05b7
Create Date: 2024-05-21 16:52:11.445425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85707ff9c0b6'
down_revision: Union[str, None] = 'e77760fd05b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totalscores',
    sa.Column('id_tournament', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_flight', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_flight'], ['flights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_tournament'], ['tournaments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id_tournament', sa.Integer(), nullable=False),
    sa.Column('id_hole', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_flight', sa.Integer(), nullable=True),
    sa.Column('id_total_score', sa.Integer(), nullable=True),
    sa.Column('impacts', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_flight'], ['flights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_hole'], ['holes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_total_score'], ['totalscores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_tournament'], ['tournaments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('totalscores')
    # ### end Alembic commands ###
