"""add image src in User model

Revision ID: 5a529c897fdb
Revises: 9b3273dc7c01
Create Date: 2024-05-21 09:52:18.715258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a529c897fdb'
down_revision: Union[str, None] = '9b3273dc7c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_src', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_src')
    # ### end Alembic commands ###
