"""optional id course for tournament

Revision ID: d4077c983701
Revises: d654637e734f
Create Date: 2024-05-25 03:54:54.104852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4077c983701'
down_revision: Union[str, None] = 'd654637e734f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('holes', sa.Column('id_course', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'holes', 'courses', ['id_course'], ['id'], ondelete='SET NULL')
    op.add_column('tournaments', sa.Column('id_course', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournaments', 'courses', ['id_course'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'id_course')
    op.drop_constraint(None, 'holes', type_='foreignkey')
    op.drop_column('holes', 'id_course')
    op.drop_table('courses')
    # ### end Alembic commands ###
