"""create table Admins

Revision ID: d91550c3116f
Revises: 51e1e5cf720f
Create Date: 2024-05-20 23:27:13.375277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd91550c3116f'
down_revision: Union[str, None] = '51e1e5cf720f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
                    sa.Column('login', sa.String(length=50), nullable=False),
                    sa.Column('password', sa.LargeBinary(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('date_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
