"""add field hcp in table Tournament

Revision ID: e77760fd05b7
Revises: 2d58e1b571b6
Create Date: 2024-05-21 14:14:54.065467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77760fd05b7'
down_revision: Union[str, None] = '2d58e1b571b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('hcp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'hcp')
    # ### end Alembic commands ###
