"""create table hole

Revision ID: cfcc23aec6eb
Revises: 2af2a52c6ec9
Create Date: 2024-05-21 01:28:24.000897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cfcc23aec6eb'
down_revision: Union[str, None] = '2af2a52c6ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holes',
                    sa.Column('number', sa.Integer(), nullable=False),
                    sa.Column('par', sa.Integer(), nullable=False),
                    sa.Column('difficulty', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('date_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holes')
    # ### end Alembic commands ###
