"""create table Users

Revision ID: 51e1e5cf720f
Revises: 
Create Date: 2024-05-20 23:22:45.389088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '51e1e5cf720f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id_telegram', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=50), nullable=False),
                    sa.Column('last_name', sa.String(length=50), nullable=True),
                    sa.Column('handicap', sa.Float(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('date_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id_telegram')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
