"""add type field in Tournament table

Revision ID: 05fe8f8806c7
Revises: 85707ff9c0b6
Create Date: 2024-05-21 19:57:51.899259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05fe8f8806c7'
down_revision: Union[str, None] = '85707ff9c0b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'type')
    # ### end Alembic commands ###
